### ISSUE TITLE
1.2 - Livia and Seth, culture and onboarding

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/research_content#216] opened 2021-10-24 21:04 UTC
# Topic: Culture & Onboarding
Episode 2: How culture contributes to and influences onboarding, the reciprocal nature of
(with SCRF host, Seth Frey (UC Davis), Livia Deschermayer (TEC))
- What role does culture play?
- What steps need to be taken to get people aware of the culture through the onboarding process?
- What are some ways to think about culture and to be intentional about it?
- Are there any particular signs of ‘healthy’ culture?
- What are some things to look out for, where things can go wrong? 
- How to get new members engaged?
- How to help people understand the ways they can contribute?
- What tools are needed to help onboard?
# Relevant Links
- Source
https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit?usp=sharing
- Episode Folder Link
https://drive.google.com/drive/folders/14Ouie9CD5S8BvqGRdgqDcZ4cPh7FyM0b?usp=sharing
# Steps to completion
**Idea Proposal Stage**
- [x] Draft a potential topic to cover
- [x] Draft some specific questions 
- [x] Draft ideal guests 
- [x] Reach out to one to gauge interest
- [x] Any updates to the questions/topic?
- [x] Ask the first guest about who they’d want to talk to
- [x] If no, then come up with a second guest 
- [x] Reach out to the second guest 
- [x] Move on to scheduling

**Drafting**
- [x] Send out schedule/pick date
- [x] Send invite w/checklist and questions
- [x] Send confirmation email 24 hrs before recording
- [x] Check "Preparing for the interview" checklist
- [x] Confirm with all guests if the topic/question list looks good

**Peer Review**
- [x] Check the ‘Getting ready to record checklist’
- [x] Press record
- [x] Shift audio levels as needed
- [x] Receiving files for post

**Final Content Review**
- [x] Editing
- [x] Edit check/revisions
- [x] Export final video/save to drive
- [x] Export final audio/save to drive
- [x] Transcribe Audio
- [x] Pull transcript from Riverside 
- [x] Review transcript
- [x] Upload transcript to HackMD
- [ ] Submit pull request to github

**Editorial Review**
- [x] Start Show Notes draft
- [x] Share with team/revise
- [x] Finalize Show Notes

**Engagement and Calendaring**
- [ ] Engagement/Social meeting

**Published**
- [ ] Market Episode on Twitter/LinkedIn
- [x] Post to YouTube 
- [x] Host on [insert platform here]

**Comment by eleventh19** [comment] 2021-11-01 16:48
@ivanplazacic can you please update the title to Livia and TBC for now? Hopefully it will be Amy but she has not confirmed yet

**Comment by eleventh19** [comment] 2021-11-02 14:41
I pinged the other guest who I am trying to get lined up again as she hasn't responded since last week. Will update if I hear from her or will think of someone else if she doesn't get back to us by the end of the week

**Comment by eleventh19** [comment] 2021-11-02 21:27
the person I had in mind passed so need to figure out who to invite

**Comment by eleventh19** [comment] 2021-11-19 22:35
just pinged Livia again to check in and will reach out to the second guest after hearing back from Livia

**Comment by eleventh19** [comment] 2021-12-01 23:55
reached out to a potential second guest and pinged Livia to catch up this week

**Comment by eleventh19** [comment] 2021-12-03 17:55
Livia and Seth both confirmed and I just shot an email for scheduling

**Comment by eleventh19** [comment] 2021-12-09 21:40
just sent a proposed time, no clarity from doodle

**Comment by eleventh19** [comment] 2021-12-15 02:21
recording tomorrow

**Comment by ivanplazacic** [comment] 2021-12-16 20:27
Here is the link to all the backup/archival files:

https://drive.google.com/drive/folders/1MSbiF6q_ew4-hSA2MuzawGKaBgdEW_iK?usp=sharing

Here is the link to the separate raw recordings:

https://drive.google.com/drive/folders/15kP0xwyBR9KRhU-t5EcvYlyJ-QGiCVPL?usp=sharing

**Comment by ivanplazacic** [comment] 2021-12-23 18:31
Here is the link to the edit:

https://drive.google.com/file/d/1mTQr4qGH6O0VXEfHawjOQWODCgDyIsy8/view?usp=sharing

**Comment by ivanplazacic** [comment] 2022-01-09 19:22
Here is the link to the edit with the first revision:

https://drive.google.com/file/d/1mTQr4qGH6O0VXEfHawjOQWODCgDyIsy8/view?usp=sharing

**Comment by encore9870** [comment] 2022-07-13 12:43
Closing this as we have moved the podcast discussion away and will be using this repository for content pipeline drafts.

**Closed by encore9870** 2022-07-13 12:43 UTC
Labels: governance
